<?
$aMenuLinks = Array(
	Array(
		"О компании", 
		"/about/", 
		Array(), 
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-1.png"), 
		"" 
	),
	Array(
		"Новости", 
		"/news/", 
		Array(), 
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-7.png"), 
		"" 
	),
	Array(
		"Сервис", 
		"/service/", 
		Array(), 
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-3.png"), 
		"" 
	),
	Array(
		"Каталог", 
		"/catalog/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Практик Центр", 
		"/practic-centr/", 
		Array(), 
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-4.png"), 
		"" 
	),
	Array(
		"Фрезерный центр", 
		"http://www.rossdent.ru/zubotehnicheskaya-laboratoriya/", 
		Array(), 
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-5.png"), 
		"" 
	),
	Array(
		"Вопрос-ответ", 
		"/forum/", 
		Array(), 
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-5.png"), 
		"" 
	),
	Array(
		"Статьи",
		"/articles/",
		Array(),
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-5.png"),
		""
	),
	Array(
		"Контакты", 
		"/contacts/", 
		Array(), 
		Array("LNK_IMG"=>"/bitrix/templates/rossdent/img/menu-8.png"), 
		"" 
	)
);
?>